### ISSUE TITLE
sandcat.go error 

### ISSUE THREAD

**Issue by romlombardi** [mitre/sandcat#22]
I'm new to this, it seems to me that the caldera tool is a very practical solution.

I just made the last update, modify the file of /conf/local.yml to server 0.0.0.0:8888, modify the file /gocat/sandcat.go server:https://0.0.0.0:8888, modify the file servers.txt 0.0.0.0: 8888
following the instructions run GOOS = windows go build -ldflags = "- s -w" sandcat.go
GOOS = linux go build -ldflags = "- s -w" sandcat.go
GOOS = darwin go build -ldflags = "- s -w" sandcat.go 
and copy the new files to stockpile / payloads and when executing the Quick start commands I get the errors:

[54ndc47] beaconing
panic: interface conversion: interface {} is nil, not [] interface {}

goroutine 1 [running]:
main.stayInTouch (0x6a3f35, 0x14, 0xc42001a490, 0x10, 0xc42001c300, 0x17, 0x6a03cc, 0x6)
        /home/ubuntu/caldera/plugins/sandcat/gocat/sandcat.go:17 + 0x2da
main.main ()
        /home/ubuntu/caldera/plugins/sandcat/gocat/sandcat.go:42 + 0x1eb

I think (I'm not a programmer) that the error is in: server: = "https: // localhost: 8888", in go with // a line is commented

Thanks for the help

**Comment by romlombardi** [comment]
hello , i just update the repository today and works fine  thanks , im closing the issue

**Comment by romlombardi** [comment]
hello , i just update the repository today and works fine  thanks , im closing the issue
